### ISSUE TITLE
不能自动下载中文字幕

### ISSUE THREAD

**Issue by wkingfly** [songchenwen/dotfiles#1]
看了下lua脚本，怎么没发现定义字幕网址的地方？

**Comment by songchenwen** [comment]
是调用 `Subliminal` 下载的。我这里是下载的英文字幕。

要修改参数的话可以看看 [这行](https://github.com/songchenwen/dotfiles/blob/master/mpv/scripts/autosub.lua#L12)。把 `en` 改成 `zh` 应该就能下载中文字幕了。不过最近 Subliminal 内置的一些网站好像被墙了。

**Comment by wkingfly** [comment]
好吧，还要首先安装这个，那这个可以更换字幕网站的网址么

**Comment by songchenwen** [comment]
`Subliminal` 内置了一堆字幕网站。不过应该不能自己随意更换网址。
